### ISSUE TITLE
Element inserts, shuffles, and splats

### ISSUE THREAD

**Issue by hanna-kruppe** [hanna-kruppe/rvv-llvm#12]
Most pressingly we need to support expressing broadcasts from a scalar into all elements of a vector, canonically written like this in LLVM IR:

```llvm-ir
  %1 = insertelement <scalable 1 x i32> undef, i32 %0, i32 0
  %2 = shufflevector <scalable 1 x i32> %1, <scalable 1 x i32> undef, <scalable 1 x i32> zeroinitializer
```

As part of that it'll be easy to support the general form of these IR instructions as well:

-  `insertelement` just maps to a `v[fd]?insert`
- `shufflevector` is simpler than it looks because the last operand, the list of indices, (currently) has to be a compile time constant, so it can only be
  - `zeroinitializer` (= a broadcast of the first element), or
  - `undef` which just makes the whole shuffle result `undef` as well (so we don't really need to do anything with it)

Implementation-wise, it'll require (besides the usual instruction encoding stuff and TableGen ISel patterns):

- a new RISCV-specific ISD node (like SETVL today) called BROADCAST or something like that (taking a scalar and returning a vector)
- some custom C++ logic in RISCVISelLowering.cpp (for `ISD::SHUFFLE_VECTOR`) that checks to see if the shuffle is a splat, and if so, turns it inso a BROADCAST node

**Comment by pranav-prakash** [comment]
Before I dive into implementing this I just wanted to Just to double check whether I have things conceptually straightened out: It looks like `VECTOR_SHUFFLE` already exposes an attribute `isSplat` (and if so it's operand presumably has a method to extract the scalar being splatted). The target lowering would then consist of a custom dag operation for ISD::VECTOR_SHUFFLE that would replace it if it is indeed a splat with our RISCV specific `BROADCAST` node whose operand is the scalar.

To then implement the selection for i-type vector instructions like `vaddi` we'd then add a new pattern to match [I'm not too clear if the syntax below is right]

```
Pat<(OpNode VR:$rs1, VR: (rv_broadcast simm8: $imm), VLR:$vl), (Inst VR:$rs1, simm8:$imm, VLR:$vl)>
```

**Comment by pranav-prakash** [comment]
>One other thing I should add is that there's a chance that the general SelectionDAG code (e.g., DAG combines or legalization) will not handle vector operations involving scalable vectors very gracefully

I believe I'm running into this issue. I'm testing on this snippet (from `rvv-reg-imm-op.ll` on my branch that I've updated with the in-progress selection dag changes)

```
%vimm.inserted = insertelement <scalable 1 x i32> undef, i32 %2, i32 0
%vimm.splatted = shufflevector <scalable 1 x i32> %v.imm1, <scalable 1 x i32> undef, <scalable 1 x i32> zeroinitializer

%v.R1 = call <scalable 1 x i32> @llvm.riscv.vadd(<scalable 1 x i32> %v.A, <scalable 1 x i32> %vimm.splatted, i32 %vl)
```

Leads `llc` to error out with:

```
error: '%vimm.splatted' defined with type '<1 x i32>' but expected '<scalable 1 x i32>'
```

What flags did you pass to llc to have it print out the debug info?

**Comment by rkruppe** [comment]
I passed `-debug`. I believe there's a more targeted flag for only getting output from specific stages of the pipeline but I don't know it off-hand.

**Comment by pranav-prakash** [comment]
Ok it seems that issue lies somewhere in (or before) `SelectionDAGBuilder::visitShuffleVector`, since at that point `user.getType()` is `<1 x i32>v1i32 nxv1i32 nxv1i32` which results in `getVectorShuffle()` being called with an EVT of `v1i32`. The calling methods are pretty much just the various `SelectionDAGBuilder::visit` and `SelectionDAGISel` methods, however. Is there some other phase before this that might have set the output value to `v1i32`? It also doesn't look like llvm did any sort of node merging yet, and looking through the other dag visualizations (-view-dag-combine-lt-dags, -view-dag-combine1-dags) doesn't show it touching any of the vectors.

```
Total amount of phi nodes to update: 3
Node 0 : (0x89a32b8, 2147483654)
Node 1 : (0x89a3320, 2147483656)
Node 2 : (0x89a3388, 2147483655)
Creating constant: t1: i32 = TargetConstant<5210>
Creating new node: t3: i32,ch = CopyFromReg t0, Register:i32 %0
Creating new node: t4: i32 = llvm.riscv.setvl TargetConstant:i32<5210>, t3
Creating constant: t5: i32 = TargetConstant<5213>
Creating new node: t7: i32,ch = CopyFromReg t0, Register:i32 %1
Creating new node: t8: nxv1i32,ch = llvm.riscv.vlw t0, TargetConstant:i32<5213>, t7, t4
Creating new node: t9: nxv1i32 = undef
Creating constant: t10: i32 = Constant<2>
Creating constant: t11: i32 = Constant<0>
Creating new node: t12: nxv1i32 = insert_vector_elt undef:nxv1i32, Constant:i32<2>, Constant:i32<0>
```

(As a sidenote, is there a way to have llvm its the stack trace with symbol names? Currently it only prints symbol addresses and I have to then use gdb to lookup the corresponding symbol name)

**Comment by pranav-prakash** [comment]
I think the issue might be in the parsing stage itself, with the call to `ShuffleVectorInst::ShuffleVectorInst`. The instruction is initialized with type `VectorType::get(cast<VectorType>(V1->getType())->getElementType()` which somehow ends up losing the scalable part. Still looking into this but I'm pretty sure that's where the crux of the bug lies.

**Comment by rkruppe** [comment]
Oh, that makes sense, good find!

> I'm not sure why they go about constructing the VectorType this way rather than just using the type of V1 or V2 directly. It'd be a straightforward fix to just use V1->getType() but I'm not sure if there was originally a reason for the indirect way they chose to construct the type.

The "mask" can have a different number of elements than the source, resulting in a longer or shorter vector than the source vectors V1 and V2. It should suffice to change `getNumElements` to `getElementCount`.

**Comment by pranav-prakash** [comment]
>It should suffice to change `getNumElements` to `getElementCount`

Yup, it solved that issue.

Now as for the instruction selection, it interestingly appears that LLVM seems to combine `insert_vector` and `shuffle_vector` into a `BUILD_VECTOR Constant:i32` node before the lowering even happens

```
Combining: t12: nxv1i32 = insert_vector_elt undef:nxv1i32, Constant:i32<2>, Constant:i32<0>
Creating new node: t36: i32 = undef
Creating new node: t37: nxv1i32 = BUILD_VECTOR Constant:i32<2>
 ... into: t37: nxv1i32 = BUILD_VECTOR Constant:i32<2>
```

In this case shouldn't it suffice to directly do the isel pattern matching on the `BUILD_VECTOR i32` node rather than creating our own `RISCV::BROADCAST`?

(I also played around with writing custom lowering logic for `ISD::BUILD_VECTOR` to emit the `RISCV::BROADCAST` but it was never called – I'm sort of conceptually unclear as to why this is the case since to my understanding the lowering logic is called as the final step after LLVM does its own combining and merging, which means it should have called `lowerBUILD_VECTOR`)

**Comment by rkruppe** [comment]
I suspect there's at least two different issues at play here:

- A BUILD_VECTOR of scalable vector type sounds wrong. BUILD_VECTOR is supposed to take one scalar for each lane and put those scalars together into a vector straightforwardly. Because SelectionDAG construction is currently mostly ignorant of scalable vectors, it probably just treats it as a length one vector, which is clearly wrong. I think the behavior would be to never create a BUILD_VECTOR of scalable vector type (can't know how many scalars to specify, so it doesn't really make sense).
- Similarly, shufflevector-specific code probably iterates from 0 to `VecTy->getNumElements()` to "look at all elements", which makes it consider nxv1i32 the same as v1i32, and for the latter a `shufflevector %A, undef, zeroinitializer` is a nop that can be removed easily.

> (I also played around with writing custom lowering logic for ISD::BUILD_VECTOR to emit the RISCV::BROADCAST but it was never called – I'm sort of conceptually unclear as to why this is the case since to my understanding the lowering logic is called as the final step after LLVM does its own combining and merging, which means it should have called lowerBUILD_VECTOR)

Could you show the code you added for that? (As I said I don't think BUILD_VECTOR should even enter the picture but let's try to find the bug here so it doesn't bite again when custom lowering for a different opcode is added.)

**Comment by rkruppe** [comment]
I'm starting to think that trying to bludgeon all the SelectionDAG code into handling shuffles etc. correctly is an unreasonably large project at this stage. I took another look over Graham Hunter's patch series for Arm SVE and (re-)discovered that he introduced a special intrinsic for representing splats instead of repurposing existing SDAG nodes. Have a look at https://reviews.llvm.org/D47775, maybe we can just import that patch (like I did with the IR type)?

**Comment by rkruppe** [comment]
> I've pushed it to my fork. I was testing by using gdb to set a breakpoint at RISCVTargetLowering::lowerBUILD_VECTOR while running llc on test/CodeGen/RISCV/rvv-reg-imm-op.ll but it was never hit.

Ah, I think one issue (besides DAG combines possibly removing the BUILD_VECTOR entirely before legalization kicks in) is [this line](https://github.com/pranav-prakash/rvv-llvm/blob/e0ece29ae4cea1956363c8114e458b349d226c1a/lib/Target/RISCV/RISCVISelLowering.cpp#L144) declaring a custom lowering of BUILD_VECTOR nodes of type `i32` rather than `nxv1i32`.
