### ISSUE TITLE
Vector register copies

### ISSUE THREAD

**Issue by hanna-kruppe** [hanna-kruppe/rvv-llvm#4]
In `RISCVInstrInfo::copyPhysReg` we need to handle copies from one VR to another. One complication here is that (in the current state of the spec) all the natural ways to do that copy will be affected by vl, i.e., only copy elements 0..vl instead of the whole vector. That's a problem if the copy is later used with a larger vl than is used for the copy, some elements of the vector will appear to have disappeared (replaced with unpredictable junk). So in general we need to set vl=MAXVL for the duration of the copy, or petition for the spec to gain an instruction that copies full vectors regardless of vl.

Of course that's inefficient &ndash; even a dedicated instruction will take more cycles on some uarchs than copying elements 0..vl, and without it we also need instructions and a scratch GPR to save, change, and restore vl. Once the copying works correctly, we should look into ways to avoid doing that on natural code.

**Comment by pranav-prakash** [comment]
I'm looking into this – Can you think of some IR that would generate a VR -> VR copy? I tried manually passing some MIR through `llc` starting after the register-coalescing pass, but it seems it's still optimized out

```
    %3:vlr, %4:gpr = VSETVL %0
    %5:vr = VLW %1, %3, 0 
    %6:vr = COPY %5
    %7:vr = COPY %5
    %8:vr = VADDI %6, 1, %3
    %9:vr = VADD %8, %7, %3
    VSW %2, %8, %3, 0
```

**Comment by rkruppe** [comment]
Hm, it's easiest when a vector call ABI is implemented (I used to have a very hacky one), since then you can just, for example, return a vector argument that was passed in a different register than the return value needs to go into.

I can't very well experiment myself right now, but I think a code pattern like this should require at least one copy that register coalescing can't remove:

```
bb1:
  %v1 = call <scalable 1 x i32> @llvm.riscv.vlw(...)
  %v2 = call <scalable 1 x i32> @llvm.riscv.vlw(...)
  %sum = call <scalable 1 x i32> @llvm.riscv.vadd(...)
  br i1 %some_condition, label %bb2, label %bb3
bb2:
  br label %bb3
bb3:
  %v3 = phi <scalable 1 x i32> [%v1, %bb1], [%sum, %bb3]
  %v4 = phi <scalable 1 x i32> [%sum, %bb1], [%v2, %bb3]
   call <scalable 1 x i32> @llvm.riscv.vsw(..., %v3, ...)
   call <scalable 1 x i32> @llvm.riscv.vsw(..., %v4, ...)
```

**Comment by pranav-prakash** [comment]
Yeah that seems to do it.

The approach I'm planning to take with this is to have the VR -> VR copies generate a `vaddi dest, src, 0` – the only catch is that I think we need to also pass in the vector length to the `vaddi` MI. For now since I think you mentioned we are keeping vector lengths unchanging within one basic block, would it be fine to just look at the other instructions in the basic block to find a `VL` register definition and use that?

**Comment by rkruppe** [comment]
> The approach I'm planning to take with this is to have the VR -> VR copies generate a `vsetvl MAX_VL` followed by a `vaddi dest, src, 0` – the only issue is that we need to save the current VL to restore it afterwards. Since I think you mentioned we are keeping vector lengths unchanging within one basic block, would it be fine to just look at the other instructions in the basic block to find a `VL` register definition and restore that?

At the stage where register copies are expanded, we're already past register allocation, so the code that came out of isel has passed through optimizations that may have broken the "VL does not change within a block" property (and even if that did hold, the most recent definition of a VL register may be in another block).

Luckily, because this happens so late that we already deal with physical registers, it should be possible to just read the current value of the physical register right at the location where the VR copy happens.



> Additionally is there a canonical way to find the maximum supported vector length? A hacky way to do it is to probably set it to `1 << XLEN` which should round down and effectively set it to `maxvl` but this doesn't seem too elegant.

vlmax is a (read-only) CSR, just read that.
